// tools/protocol-gen/generate.ts — emits the GDScript mirrors of the server's
// wire contract and tuning constants. The server is the source of truth; the
// Godot shell's Rules/Catalog are cross-checked against the output by
// game/tests/data_sanity.gd. Run from server/ so its node_modules resolve:
//
//   cd server && npx tsx ../tools/protocol-gen/generate.ts
//
// Output is deterministic (stable key ordering) so regeneration is diff-clean.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { OP, PROTOCOL_VERSION } from '../../server/shared/protocol.js';
import { WS_PATH } from '../../server/shared/constants.js';
import * as tuning from '../../server/shared/tuning.js';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

const HEADER = [
  '# GENERATED by tools/protocol-gen — do not edit; regenerate with:',
  '#   cd server && npx tsx ../tools/protocol-gen/generate.ts',
].join('\n');

// Enough levels that any curve check (and the shell's level-up UI) reads the
// server's rounding instead of re-deriving it.
const XP_CURVE_LEVELS = 30;

function isScalar(v: unknown): v is number | boolean | string {
  return typeof v === 'number' || typeof v === 'boolean' || typeof v === 'string';
}

function gdScalar(v: number | boolean | string): string {
  if (typeof v === 'number') {
    if (!Number.isFinite(v)) throw new Error(`non-finite number: ${v}`);
    return String(v);
  }
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return JSON.stringify(v);
}

/** Plain object whose values are all scalars → nested GDScript Dictionary. */
function isScalarGroup(v: unknown): v is Record<string, number | boolean | string> {
  return (
    typeof v === 'object' && v !== null && !Array.isArray(v) && Object.values(v).every(isScalar)
  );
}

function gdDict(entries: readonly [string, string][], indent: string): string {
  const lines = entries.map(([k, v]) => `${indent}\t${JSON.stringify(k)}: ${v},`);
  return `{\n${lines.join('\n')}\n${indent}}`;
}

// ---- server_protocol.gd -----------------------------------------------------

// A numeric TS enum object carries the reverse mapping too — keep name→number only.
const opEntries = Object.entries(OP)
  .filter((e): e is [string, number] => typeof e[1] === 'number')
  .sort((a, b) => a[1] - b[1]);
if (new Set(opEntries.map(([, n]) => n)).size !== opEntries.length) {
  throw new Error('duplicate OP wire numbers in protocol.ts');
}

const protocolGd = `${HEADER}
class_name ServerProtocol
## Wire vocabulary mirrored from server/shared/protocol.ts (WS_PATH from
## constants.ts). Numeric op values ARE the contract — never reuse a number.

const VERSION := ${PROTOCOL_VERSION}
const WS_PATH := ${JSON.stringify(WS_PATH)}

## op name → frozen wire number (client 1–39, server 100–139).
const OP := ${gdDict(
  opEntries.map(([k, n]) => [k, String(n)] as [string, string]),
  '',
)}
`;

// ---- server_tuning.gd -------------------------------------------------------

const valueEntries: [string, string][] = [];
for (const key of Object.keys(tuning).sort()) {
  const v = (tuning as Record<string, unknown>)[key];
  if (typeof v === 'function') continue;
  if (isScalar(v)) {
    valueEntries.push([key, gdScalar(v)]);
  } else if (isScalarGroup(v)) {
    const nested = Object.keys(v)
      .sort()
      .map((k) => [k, gdScalar(v[k])] as [string, string]);
    valueEntries.push([key, gdDict(nested, '\t')]);
  } else {
    throw new Error(`unhandled tuning export shape: ${key} — extend the generator`);
  }
}

const xpCurve = Array.from({ length: XP_CURVE_LEVELS }, (_, i) => tuning.xpForLevel(i + 1));

const tuningGd = `${HEADER}
class_name ServerTuning
## Balance constants mirrored from server/shared/tuning.ts — the server-side
## source of truth. game/tests/data_sanity.gd asserts Rules.* agree with these.

const VALUES := ${gdDict(valueEntries, '')}

## xpForLevel(1..${XP_CURVE_LEVELS}) (index = level − 1) — locks the server's curve
## rounding as truth for Rules.xp_for_level.
const XP_CURVE: Array[int] = [${xpCurve.join(', ')}]
`;

// ---- write ------------------------------------------------------------------

for (const [rel, content] of [
  ['game/src/net/server_protocol.gd', protocolGd],
  ['game/src/data/server_tuning.gd', tuningGd],
] as const) {
  const path = join(repoRoot, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`wrote ${rel}`);
}
