# GENERATED by tools/protocol-gen — do not edit; regenerate with:
#   cd server && npx tsx ../tools/protocol-gen/generate.ts
class_name ServerProtocol
## Wire vocabulary mirrored from server/shared/protocol.ts (WS_PATH from
## constants.ts). Numeric op values ARE the contract — never reuse a number.

const VERSION := 1
const WS_PATH := "/ws"

## op name → frozen wire number (client 1–39, server 100–139).
const OP := {
	"JOIN": 1,
	"RESUME": 2,
	"GPS": 3,
	"ATTACK": 4,
	"USE_SLOT": 5,
	"FLEE": 6,
	"EQUIP": 7,
	"EQUIP_GEAR": 8,
	"BUY": 9,
	"SELL": 10,
	"TOWER_BUILD": 11,
	"TOWER_REPAIR": 12,
	"TOWER_UPGRADE": 13,
	"TOWER_SALVAGE": 14,
	"TOWER_TARGET": 15,
	"TOWER_REPAIR_ALL": 16,
	"MINION_SEND": 17,
	"MINION_COLLECT": 18,
	"MINION_HIRE": 19,
	"MINION_HEAL": 20,
	"QUEST_CLAIM": 21,
	"CHEST_OPEN": 22,
	"PARTY_CREATE": 23,
	"PARTY_JOIN": 24,
	"PARTY_LEAVE": 25,
	"RUN_START": 26,
	"RUN_END": 27,
	"RESPAWN": 28,
	"REVIVE": 29,
	"REQUEST_SNAPSHOT": 30,
	"PONG": 31,
	"HELLO": 100,
	"SNAPSHOT": 101,
	"DELTA": 102,
	"EVENTS": 103,
	"ERR": 104,
	"PING": 105,
	"LOOT_RESULT": 106,
	"INVENTORY_UPDATE": 107,
	"FRONT_UPDATE": 108,
	"RUN_SUMMARY": 109,
	"DEATH": 110,
	"LEVEL_UP": 111,
	"PARTY_UPDATE": 112,
	"SHOP_RESULT": 113,
	"MINION_REPORT": 114,
}
